patternfly/patternfly-react-seed

- .gitignore
- README.md
- package.json
- yarn.lock
This PR adds basic support for analyzing bundle size using webpack bundle analyzer. Gives us a nice interface as seen in the screenshot below.
> feat(bundle-analyzer): add scripts for analyzing bundle size after build

- package.json
- src/index.js
- yarn.lock
This PR adds react-axe lib, which inspects the generated markup and checks it for accessibility errors. There are currently none, so you'll see nothing in the console if trying to verify it works. To test, add a button without text to the page and watch the errors appear in the browser's js console.
> feat(a11y-checks): run accessibility during development

- webpack.common.js
This PR allows file-loader to process fonticons now provided by patternfly. Previously, this loader was only processing modules under the fonts directory, now they exist also under pficon directory, so we test for that also.
> feat(fonticon): support fonticons now provided by patternfly

- webpack.dev.js
This PR makes the source maps better by having them point to the original source files during dev.
> fix(sourcemaps): ensure sourcemaps point back to precompiled source

- package.json
- tsconfig.json
- yarn.lock
This PR fixes an issue where users getting started with pf seed would encounter errors upon following the hello world examples for some of the [chart](https://github.com/patternfly/patternfly-react/issues/1603) components.
Not sure what's missing, but the following screenshot shows what we get when the example is rendered, notice the missing domain/range labels.
In any case, this should help speed up the getting started experience for people.
> chore(config): adjust ts configuration to better align with pf examples

- README.md
This PR shows users how to incorporate various types of images into the app with code snippets to help get them started. This should speed up the getting started process.
> chore(documentation): illustrate various ways of importing images

- src/typings.d.ts
This PR declares module support for various common file types. In some setups these don't seem to be necessary, however, some users have reported needing to explicitly declare here in typings even just to import a CSS module for example. One less stumbling block.
> feat(module-support): add more support for various file types

- jest.config.js
- src/app/app.test.tsx
This PR adds a new entry for the jest `moduleNameMapper` config. The problem was that when jest encountered a module which used a path alias `@app/*` it failed the lookup, as seen in the screenshot below.
The test suite should also be able to resolve these types of references just like for the app runtime. With this PR in place, users can now do this as seen below.
> chore(paths): register path alias with jest

- README.md
- package.json
- src/app/index.tsx
- src/index.tsx
- webpack.common.js
- webpack.dev.js
- webpack.prod.js
- yarn.lock
This PR tunes the common, dev, and production webpack configs to be a little more efficient. In particular, we're making better use of the `include` property for each loader. Many of the loaders didn't include this at all before which resulted in webpack needing to comb through many directories for modules it would never need to do anything with. I also removed json files from the resolve.extensions and turned off `symlinks` and `cacheWithContext`. These changes in concert roughly reduce the build/start time by 50%. 
Should help close https://github.com/patternfly/patternfly-react-seed/issues/50
upgrade webpack deps
limit scope of what webpack loaders need to look through
set some performance optimization settings
> feat(performance): webpack config upgrades

- package.json
- src/app/AppLayout/AppLayout.tsx
- src/app/Dashboard/Dashboard.tsx
- src/app/DynamicImport.tsx
- src/app/NotFound/NotFound.tsx
- src/app/Support/Support.tsx
- src/app/__snapshots__/app.test.tsx.snap
- src/app/app.css
- src/app/app.test.tsx
- src/app/index.tsx
- src/app/routes.tsx
- src/index.tsx
- webpack.prod.js
- yarn.lock
This PR adds minimal support for routing, bootstrapping seed with Patternfly's standard Page component. I've stubbed out a 404-page route, and lazy loaded the support page - all for illustration sake.
Helps close https://github.com/patternfly/patternfly-react-seed/issues/52
> feat(chrome): add chrome, example routes, and manage sidebar

- package.json
- src/app/AppLayout/AppLayout.tsx
- src/app/DynamicImport.tsx
- src/app/NotFound/NotFound.tsx
- src/app/routes.tsx
- src/app/utils/utils.ts
- webpack.common.js
- yarn.lock
This PR adds a small pkg to track the last route so that we can fine-tune the AX by not sending focus upon initially loading the app. It also registers a couple of new directories in the webpack config that users are likely to need at some point. Finally, I switched the default "home" route to be "/" instead of "/dashboard". 
only focus on new content when a user navigates in-app
add a small delay before sending focus for JAWS
> chore(webpack): tune webpack config

- src/index.html
This PR adds a `base` element to the head section of the main index file. This ensures assets are loaded relative to the web app root, and not somewhere else.
Loading SPAs in subdirectories may require more advanced configuration with some sort of client/server handshake and is beyond scope of what seed aims to solve out of the box. These changes assume users are loading the UI at the root of the webserver.
Should help close https://github.com/patternfly/patternfly-react-seed/issues/68
> chore(paths): ensure asset paths are relative to the root of app

- .gitignore
- .storybook/config.ts
- .storybook/tsconfig.json
- .storybook/webpack.config.js
- package.json
- src/app/Support/Support.tsx
- stories/Dashboard.stories.tsx
- stories/Support.stories.tsx
- webpack.common.js
- yarn.lock
> feat: add Storybook

- .eslintrc
- README.md
- dr-surge.js
- jest.config.js
- package-lock.json
- package.json
- src/app/Dashboard/Dashboard.tsx
- src/app/app.test.tsx
- tsconfig.json
- webpack.dev.js
This PR 
- upgrades PF deps
- fixes a typo in the readme that shows the wrong command for starting the dev server
- adds a small utility to the end of the build task to generate a 200.html file which helps surge deployments properly load route content when navigating directly to a subroute.
- removes some of what looks to be redundant jest configs in favor of what ts-jest gives us out of box
- registers supported environments for eslint
- allow network access in dev mode
- use importHelpers tsconfig setting
- specify supported environments
Known issues: In dev mode we get the following axe error when loading a lazy loaded component. Probably could use a better solution for this.
http://patternfly-react-seed.surge.sh/
> fix(readme): fix type, update pf deps, add support for bookmarkable urls

- .gitignore
- README.md
- package-lock.json
- package.json
- src/app/Dashboard/Dashboard.tsx
- src/app/routes.tsx
- webpack.common.js
- webpack.dev.js
- webpack.prod.js
This PR integrates [dotenv-webpack](https://www.npmjs.com/package/dotenv-webpack) into the build/dev pipeline. Should help close https://github.com/patternfly/patternfly-react-seed/issues/83.
To utilize this feature, simply export your environment variables at the system/user level or drop the key-value pairs into a `.env` file in the root. These will be exposed via `process.env` for use within the application UI.
> feat(env-vars): add support for basic environment variables

- package-lock.json
- package.json
Fixes this TypeScript warning/recommendation seen in `src/app/routes.tsx`:
The props passed to `<Route>` and `<Switch>` were not being checked because those type interfaces are not included in the react-router-dom library.
> Install @types/react-router-dom

- package.json
- tsconfig.json
Currently, a TypeScript error will not prevent the bundle from compiling, and there is no script for running `tsc` to type-check your app on the command line or in CI.
This PR provides two new package.json scripts, `type-check` and `ci-checks`. The former runs `tsc --noEmit`, which will fail if there are any TS errors in the source. The latter runs the `type-check`, `lint` and `test` scripts, and makes it easy for a consumer to hook that up to CI to make sure their pull requests are not breaking type-safety or their linter in addition to their unit tests.
It might also be a good idea to put an example Travis CI or Circle CI config in here which runs `npm run ci-checks`.
Note: I did have to add the `skipLibCheck` option to tsconfig.json so the `type-check` script wouldn't check .d.ts files …
> Add 'npm run type-check' and 'npm run ci-checks' scripts

- src/app/AppLayout/AppLayout.tsx
- src/app/Settings/General/GeneralSettings.tsx
- src/app/Settings/Profile/ProfileSettings.tsx
- src/app/routes.tsx
Currently the seed app has a nice abstraction around route configuration, which allows us to define routes in one place and automatically generates both the react-router tree and the vertical nav tree, and which calls custom hooks for accessibility and page title updates. However, the current implementation only supports a flat list of top-level routes, and if consumers want to use `<NavExpandable>` they will need to refactor or replace this nice route config abstraction.
This PR enhances the `IAppRoute` type defined in `routes.tsx` so that a group of related routes can be expressed as an object in the `routes` array with its own sub-`routes` array. This structure is then flattened so that all the actual routes are still rendered as top-level `<Route>` components. In `AppLayout.tsx` …
> Add support for expandable nav groups in route definition

- package-lock.json
- package.json
- src/app/Support/Support.tsx
- src/app/index.tsx
- webpack.common.js
- webpack.dev.js
Currently the hot-loader is included in production, which is unintended.
Moving this to dev makes sure that the dependency is not included in the
production build and is not used unnecessarily
> fix: move @hot-loader/react-dom to dev webpack

- src/app/AppLayout/AppLayout.tsx
The `src/apps/routes.tsx` includes an `exact` property, but this property is not applied to the `NavLink` presently. This simple change makes the `exact` property functional.
> Use route exact property in NavLink

- README.md
Since this README file is for the javascript branch only, I think it is better to specify the branch for the clone command so that the user will pull the javascript version of Patternfly Seed instead of a typescript version.
> Specify the branch for the clone in README

- src/app/routes.tsx
fix: pass missing props to Router
I noticed that props was missing in Router which was causing issue not find route params.
> fix: pass missing props to Router

- .github/workflows/ci.yaml
Consider a review of this PR to also be a review of https://github.com/patternfly/patternfly-react-seed/pull/147, which I merged by accident 🤦. I'll address any feedback on both changes here, and I promise not to merge this one early 😄 
In https://github.com/patternfly/patternfly-react-seed/pull/147 I added 4 parallel CI jobs for typechecking, linting, running tests and running a build. I opened https://github.com/patternfly/patternfly-react-seed/pull/148 to see it in action, and realized that any failure of the TypeScript job would also cause both the test and the build jobs to fail. Moreover, the test job shows the full tsc output even though the tsc job doesn't (something about running it via jest?).
At any rate, the standalone typechecking job is unnecessary. This PR removes it and …
> Remove redundant TypeScript job in CI actions

- README.md
Resolves #116 
In addition to `start` being incorrectly used in the README instead of `start:dev`, the README was still describing the use of `yarn` even though the repo switched to using the npm CLI at some point. Also, `--legacy-peer-deps` is required on this branch with newer versions of npm since it is currently using outdated dependencies that don't explicitly support React 17. (we need to port changes from #150 to this branch if we intend to maintain it).
> Fix README on javascript branch

- package.json
- src/app/AppLayout/AppLayout.tsx
- src/app/NotFound/NotFound.tsx
- src/app/Support/Support.tsx
- src/app/__snapshots__/app.test.tsx.snap
Bumps to latest alphas & updates EmptyState components per new API:
```
"@patternfly/react-core": "6.0.0-alpha.28",
"@patternfly/react-icons": "6.0.0-alpha.11",
"@patternfly/react-styles": "6.0.0-alpha.11"
```
Replacement of prior open PR https://github.com/patternfly/patternfly-react-seed/pull/197
> chore(deps): update patternfly deps to v6 alphas

- package-lock.json
- package.json
- src/app/__snapshots__/app.test.tsx.snap
Bumps versions:
```
"@patternfly/react-core": "6.0.0-alpha.83",
"@patternfly/react-icons": "6.0.0-alpha.30",
"@patternfly/react-styles": "6.0.0-alpha.29",
```
to get v6 up to latest PF alphas.
> chore(docs): bump to latest alpha versions

- package-lock.json
- package.json
I also ran `npm audit fix`; cut from 17 vulnerabilities (2 low, 5 moderate, 10 high) to 9 vulnerabilities (3 moderate, 6 high). We should look at those separately.
> fix(deps): Update to PatternFly release candidate
